(()=>{
const css=document.createElement('style');css.textContent=`
#stageButtons{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:12px;margin-top:14px}
#stageButtons .stage-btn{min-height:92px;border:1px solid #3d4a55;background:#242d35;color:#f3f6f8;border-radius:16px;padding:16px;text-align:left;cursor:pointer;display:flex;align-items:center;gap:12px;box-shadow:0 8px 22px rgba(0,0,0,.16)}
#stageButtons .stage-btn:hover{background:#303b45;transform:translateY(-1px)}
#stageButtons .stage-icon{width:38px;height:38px;border-radius:11px;display:grid;place-items:center;background:#163b2d;color:#5ee09b;font-size:20px;font-weight:900;flex:0 0 auto}
#stageButtons .stage-btn.classroom .stage-icon{background:#17364a;color:#78baf0}
#stageButtons .stage-btn.teach .stage-icon{background:#3b2e16;color:#f7b84b}
#stageButtons .stage-btn.pack .stage-icon{background:#3b3016;color:#f59e0b}
#stageButtons .stage-btn strong{display:block;font-size:16px}.stage-btn small{display:block;color:#aeb8c2;margin-top:3px;line-height:1.25}
#courseCards .course-stage-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.course-stage-actions button{border:1px solid #43515d;background:#202a33;color:#d8e0e6;border-radius:9px;padding:9px 12px;font-weight:700;cursor:pointer}.course-stage-actions .teach-now{background:#d71920;color:#fff;border-color:#d71920}
#wfClassroom{position:fixed;inset:0;z-index:10001;background:#0e1419;color:#f3f6f8;overflow:auto;padding:24px 16px;isolation:isolate}
#wfClassroom::before{content:"";position:fixed;inset:0;background-image:url('https://stjohn.org.au/app/uploads/2025/08/SJA_T_AT_WhatIs.jpg');background-size:cover;background-position:center;opacity:.12;pointer-events:none;z-index:-1}
#wfClassroom .wf{position:relative;z-index:1;max-width:820px;margin:auto}
#wfClassroom .wfbrand{text-align:center;margin:18px 0 28px}.wfbrand h1{font-size:32px;margin:8px 0}.wfbrand p{color:#aeb8c2}
#wfClassroom .wcard{background:#242d35;border:1px solid #3d4a55;border-radius:18px;padding:22px;margin-bottom:16px;box-shadow:0 10px 30px rgba(0,0,0,.28)}
#wfClassroom .wbtn{width:100%;padding:16px;margin:6px 0;border:0;border-radius:12px;font-size:17px;font-weight:700;cursor:pointer}.wf-primary{background:#d71920;color:#fff}.wf-secondary{background:#202a33!important;border:1px solid #43515d!important;color:#d8e0e6}
#wfClassroom .cl-row{display:flex;align-items:center;gap:12px;padding:14px 4px;border-top:1px solid #394650;min-height:62px}.cl-row:first-child{border-top:0}.cl-row input{width:30px;height:30px;accent-color:#35c978;flex:0 0 auto}.cl-label{font-size:18px;font-weight:750;line-height:1.35;flex:1}.cl-row.done .cl-label{text-decoration:line-through;color:#7f8993}
#wfClassroom .cl-tools{display:flex;gap:8px;flex-wrap:wrap;margin-top:16px;padding-top:16px;border-top:1px solid #394650}.cl-tools button{padding:10px 13px;border-radius:9px;border:1px solid #43515d;background:#202a33;color:#d8e0e6;font-weight:700}.cl-tools .ready{background:#d71920;color:#fff;border-color:#d71920}.cl-move{display:flex;gap:5px}.cl-move button{width:40px;height:40px;padding:0}.cl-status{font-size:12px;font-weight:800;padding:8px 11px;border-radius:999px;background:#17364a;color:#78baf0;display:inline-block}
@media(max-width:900px){#stageButtons{grid-template-columns:repeat(3,1fr)}}@media(max-width:600px){#stageButtons{grid-template-columns:1fr 1fr}.stage-btn{min-height:78px!important;padding:12px!important}.stage-btn small{font-size:12px}}
`;
document.head.appendChild(css);
state.classroomChecks=state.classroomChecks||{};state.classroomItems=state.classroomItems||{};
const generic=[
 'Training room is clean, hygienic and comfortable',
 'Adequate clear floor space for CPR practice',
 'Tables and chairs arranged for the course',
 'Training room lighting, temperature and ventilation suitable',
 'Emergency exits and access routes clear',
 'Toilets and participant facilities available',
 'TV/projector and screen ready',
 'Laptop/HDMI connection and power available',
 'Reliable internet/mobile connectivity available',
 'Registration/sign-in area ready',
 'Teaching area and demonstration space ready',
 'Practical skills stations and learner equipment positioned',
 'Waste bins and cleaning supplies available'
];
function items(){const id=state.course;if(!state.classroomItems[id])state.classroomItems[id]=generic.map(x=>x);return state.classroomItems[id]}
function checks(){return state.classroomChecks[state.course]||{}}
function saveC(){if(typeof save==='function')save();else if(typeof saveW==='function')saveW();}
function complete(){const a=items(),c=checks();return a.length>0&&a.every((_,i)=>!!c[i])}
function move(i,d){const a=items(),j=i+d;if(j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];const c=checks(),n={};a.forEach((_,k)=>{n[k]=!!c[k]});state.classroomChecks[state.course]=n;saveC();openClassroom('checklist')}
function close(){document.getElementById('wfClassroom')?.remove()}
function pre(){openClassroom('pre')}
function openClassroom(mode){close();const e=document.createElement('div');e.id='wfClassroom';const name=course().name;const a=items(),c=checks();let body='';if(mode==='pre'){body=`<div class="wcard"><span class="cl-status">CLASSROOM SETUP</span><h2>Are you ready to set up the classroom?</h2><p>Use this checklist to make sure the room, technology and practical training area are ready before you begin teaching.</p><button class="wbtn wf-primary" id="begin">BEGIN CLASSROOM SETUP</button><button class="wbtn wf-secondary" id="cancel">Return to course</button></div>`}else if(mode==='post'){body=`<div class="wcard"><h2>✓ Classroom setup complete!</h2><p>The classroom is ready and the practical training area has been checked.</p><button class="wbtn wf-primary" id="teach">I'M READY TO TEACH</button></div>`}else{body=`<div class="wcard"><div style="display:flex;justify-content:space-between;align-items:center;gap:12px"><div><span class="cl-status">CLASSROOM SETUP</span><h2>${esc(name)}</h2></div><strong>${a.filter((_,i)=>c[i]).length}/${a.length}</strong></div><div class="cl-list">${a.map((x,i)=>`<div class="cl-row ${c[i]?'done':''}" data-i="${i}"><input type="checkbox" ${c[i]?'checked':''}><span class="cl-label">${esc(x)}</span><span class="cl-move"><button class="up">▲</button><button class="down">▼</button></span></div>`).join('')}</div><div class="cl-tools"><button id="all">✓ Select all</button><button id="back">Back</button>${complete()?'<button id="ready" class="ready">CLASSROOM SETUP COMPLETE</button>':''}</div></div>`}
e.innerHTML=`<div class="wf"><div class="wfbrand"><img src="optimise.webp" alt="St John" style="width:70px"><h1>${mode==='pre'?'Classroom Setup':mode==='post'?'Ready to Teach':name}</h1><p>${mode==='pre'?'Prepare the learning environment before teaching.':mode==='post'?'One stage complete. The next stage is teaching.':'Classroom setup checklist'}</p></div>${body}</div>`;document.body.appendChild(e);
if(mode==='pre'){e.querySelector('#begin').onclick=()=>openClassroom('checklist');e.querySelector('#cancel').onclick=close}
if(mode==='post'){e.querySelector('#teach').onclick=()=>{close();const card=document.querySelector('#todayPhaseCard');if(card)card.scrollIntoView({behavior:'smooth',block:'start'});}}
if(mode==='checklist'){e.querySelector('#all').onclick=()=>{state.classroomChecks[state.course]={};a.forEach((_,i)=>state.classroomChecks[state.course][i]=true);saveC();openClassroom('post')};e.querySelector('#back').onclick=pre;e.querySelector('#ready')?.addEventListener('click',()=>openClassroom('post'));e.querySelectorAll('input').forEach(box=>box.onchange=()=>{const i=Number(box.closest('.cl-row').dataset.i);state.classroomChecks[state.course]=state.classroomChecks[state.course]||{};state.classroomChecks[state.course][i]=box.checked;saveC();openClassroom(complete()?'post':'checklist')});e.querySelectorAll('.up').forEach(b=>b.onclick=()=>move(Number(b.closest('.cl-row').dataset.i),-1));e.querySelectorAll('.down').forEach(b=>b.onclick=()=>move(Number(b.closest('.cl-row').dataset.i),1))}}
function addStageButtons(){const grid=document.querySelector('#today .grid.three');if(!grid||document.getElementById('stageButtons'))return;const wrap=document.createElement('div');wrap.id='stageButtons';wrap.innerHTML=`<button class="stage-btn" id="stageToday"><span class="stage-icon">✓</span><span><strong>Today</strong><small>Active course checklist</small></span></button><button class="stage-btn classroom" id="stageClass"><span class="stage-icon">▣</span><span><strong>Classroom Setup</strong><small>Prepare the training room</small></span></button><button class="stage-btn teach" id="stageTeach"><span class="stage-icon">▶</span><span><strong>Teach</strong><small>Open teaching checklist</small></span></button><button class="stage-btn" id="stageEquip"><span class="stage-icon">✓</span><span><strong>Equipment</strong><small>Open preparation checklist</small></span></button><button class="stage-btn pack" id="stagePack"><span class="stage-icon">↻</span><span><strong>Pack Down</strong><small>Open final checklist</small></span></button>`;grid.replaceWith(wrap);wrap.querySelector('#stageToday').onclick=()=>document.querySelector('#todayPhaseCard')?.scrollIntoView({behavior:'smooth',block:'start'});wrap.querySelector('#stageClass').onclick=pre;wrap.querySelector('#stageTeach').onclick=()=>{const card=document.querySelector('#todayPhaseCard');if(card)card.scrollIntoView({behavior:'smooth',block:'start'});};wrap.querySelector('#stageEquip').onclick=()=>document.querySelector('#equipment')?.scrollIntoView({behavior:'smooth',block:'start'});wrap.querySelector('#stagePack').onclick=()=>document.querySelector('#winddown')?.scrollIntoView({behavior:'smooth',block:'start'})}
function addCourseButtons(){const host=document.getElementById('courseCards');if(!host)return;host.querySelectorAll('.course-card').forEach(card=>{if(card.querySelector('.course-stage-actions'))return;const name=card.querySelector('h3')?.textContent||'';const id=Object.keys(courses).find(k=>courses[k].name===name);if(!id)return;const box=document.createElement('div');box.className='course-stage-actions';box.innerHTML=`<button class="teach-now">▶ Teach</button><button>▣ Classroom Setup</button>`;box.children[0].onclick=()=>{state.course=id;state.activeCourse=id;saveC();document.querySelector('[data-view="today"]')?.click();setTimeout(()=>document.querySelector('#todayPhaseCard')?.scrollIntoView({behavior:'smooth',block:'start'}),100)};box.children[1].onclick=()=>{state.course=id;state.activeCourse=id;saveC();pre()};card.appendChild(box)})}
const oldUpdate=window.updateAll;window.updateAll=function(){if(oldUpdate)oldUpdate();setTimeout(()=>{addStageButtons();addCourseButtons()},50)};document.addEventListener('DOMContentLoaded',()=>{addStageButtons();addCourseButtons()});setInterval(()=>{addStageButtons();addCourseButtons()},700);
})();