(()=>{
const paletteKey='sj-instructor-palette';
const palettes={ocean:{label:'Ocean Blue',vars:{'--red':'#3b82f6','--red-dark':'#2563eb','--blue':'#4f9cf9','--teal':'#22c7b8','--amber':'#e4b94f'}},stjohn:{label:'St John Red',vars:{'--red':'#d71920','--red-dark':'#b51218','--blue':'#4b8fd8','--teal':'#2aa198','--amber':'#d6a23a'}},forest:{label:'Forest Green',vars:{'--red':'#2f9e68','--red-dark':'#237a50','--blue':'#4d91c6','--teal':'#36b9a5','--amber':'#d2ad4c'}},dusk:{label:'Dusk Purple',vars:{'--red':'#9b6cff','--red-dark':'#7650d9','--blue':'#6f9fe8','--teal':'#45b9ad','--amber':'#e1b65a'}}};
function applyPalette(name){name=palettes[name]?name:'stjohn';const root=document.documentElement;Object.entries(palettes[name].vars).forEach(([k,v])=>root.style.setProperty(k,v));document.body.classList.remove('palette-ocean','palette-stjohn','palette-forest','palette-dusk');document.body.classList.add('palette-'+name);localStorage.setItem(paletteKey,name);document.querySelectorAll('.palette-choice').forEach(x=>x.value=name)}
function equipmentComplete(){const a=equipmentList();return a.length>0&&a.every(x=>x.done)}function teachingComplete(){const a=editableTopics(),c=state.checks[state.course]||{};return a.length>0&&a.every((_,i)=>!!c[i])}function packComplete(){const a=editablePackDown(),c=state.packChecks[state.course]||{};return a.length>0&&a.every((_,i)=>!!c[i])}
function phaseDashboard(){let box=document.getElementById('todayFlow');if(!box){box=document.createElement('div');box.id='todayFlow';const anchor=document.querySelector('#today .section-head');if(anchor)anchor.parentNode.insertBefore(box,anchor.nextSibling)}const phases=[{id:'prep',name:'1. Preparation',desc:'Equipment & room ready before teaching',complete:equipmentComplete()},{id:'teach',name:'2. Course content',desc:'Work through the teaching topics',complete:teachingComplete()},{id:'pack',name:'3. Pack down',desc:'Finish, clean, document and submit',complete:packComplete()}];box.innerHTML='<div class="today-flow-head"><div><p class="eyebrow">TODAY’S WORKFLOW</p><h3>Preparation → Course content → Pack down</h3></div></div><div class="today-flow-grid">'+phases.map(p=>`<button class="phase-card ${p.complete?'phase-complete':''}" data-phase="${p.id}"><span class="phase-arrow">${p.complete?'➜':'→'}</span><span><strong>${p.name}</strong><small>${p.desc}</small></span><em>${p.complete?'COMPLETE':'OPEN'}</em></button>`).join('')+'</div>';box.querySelectorAll('[data-phase]').forEach(b=>b.onclick=()=>{const id=b.dataset.phase;if(id==='prep')showView('equipment');if(id==='teach')showView('today');if(id==='pack')showView('winddown')})}
function decorateChecklistRows(){document.querySelectorAll('#todayChecklist .check-row,#equipmentList .equipment-row,#packDownList .check-row').forEach(row=>{if(!row.querySelector('.reorder-controls')){const wrap=document.createElement('span');wrap.className='reorder-controls';wrap.innerHTML='<button type="button" class="move-up" aria-label="Move item up">▲</button><button type="button" class="move-down" aria-label="Move item down">▼</button>';row.appendChild(wrap)}});document.querySelectorAll('#todayChecklist .edit-title,#todayChecklist .edit-detail,#packDownList .edit-title').forEach(x=>{x.readOnly=true;x.tabIndex=-1;x.classList.add('locked-item')})}
function moveItem(kind,index,dir){if(kind==='teaching'){const base=course().topics.length,custom=state.customTopics[state.course]||[],topics=course().topics;if(index===base-1&&dir===1&&custom.length){const a=topics.pop(),b=custom.shift();topics.push(b);custom.unshift(a)}else if(index===base&&dir===-1&&custom.length){const a=custom.shift(),b=topics.pop();topics.push(a);custom.unshift(b)}else{const arr=index<base?topics:custom,j=index<base?index:index-base,t=j+dir;if(t<0||t>=arr.length)return;[arr[j],arr[t]]=[arr[t],arr[j]]}}else if(kind==='pack'){const base=(packDownByCourse[state.course]||defaultPackDown).length,custom=state.customPackDown[state.course]||[],baseArr=packDownByCourse[state.course]||defaultPackDown;if(index===base-1&&dir===1&&custom.length){const a=baseArr.pop(),b=custom.shift();baseArr.push(b);custom.unshift(a)}else if(index===base&&dir===-1&&custom.length){const a=custom.shift(),b=baseArr.pop();baseArr.push(a);custom.unshift(b)}else{const arr=index<base?baseArr:custom,j=index<base?index:index-base,t=j+dir;if(t<0||t>=arr.length)return;[arr[j],arr[t]]=[arr[t],arr[j]]}}else{const arr=equipmentList(),t=index+dir;if(t<0||t>=arr.length)return;[arr[index],arr[t]]=[arr[t],arr[index]]}save()}
function fixReorderClicks(){document.querySelectorAll('#todayChecklist .move-up,#todayChecklist .move-down').forEach(b=>b.onclick=e=>{e.stopPropagation();const row=b.closest('.check-row'),rows=[...document.querySelectorAll('#todayChecklist .check-row')];moveItem('teaching',rows.indexOf(row),b.classList.contains('move-up')?-1:1)});document.querySelectorAll('#packDownList .move-up,#packDownList .move-down').forEach(b=>b.onclick=e=>{e.stopPropagation();const row=b.closest('.check-row'),rows=[...document.querySelectorAll('#packDownList .check-row')];moveItem('pack',rows.indexOf(row),b.classList.contains('move-up')?-1:1)});document.querySelectorAll('#equipmentList .move-up,#equipmentList .move-down').forEach(b=>b.onclick=e=>{e.stopPropagation();const row=b.closest('.equipment-row'),rows=[...document.querySelectorAll('#equipmentList .equipment-row')];moveItem('equipment',rows.indexOf(row),b.classList.contains('move-up')?-1:1)})}
function addNamed(kind){const name=prompt(kind==='teaching'?'Name the new teaching item:':kind==='pack'?'Name the new pack-down item:':'Name the new equipment item:');if(!name||!name.trim())return;if(kind==='teaching'){state.customTopics[state.course]=state.customTopics[state.course]||[];state.customTopics[state.course].push([name.trim(),''])}else if(kind==='pack'){state.customPackDown[state.course]=state.customPackDown[state.course]||[];state.customPackDown[state.course].push(name.trim())}else equipmentList().push({text:name.trim(),done:false});save()}
function progress(){const lists=[{a:editableTopics(),c:state.checks[state.course]||{}},{a:equipmentList(),c:Object.fromEntries(equipmentList().map((x,i)=>[i,x.done]))},{a:editablePackDown(),c:state.packChecks[state.course]||{}}];let total=0,done=0;lists.forEach(x=>{total+=x.a.length;done+=x.a.reduce((n,_,i)=>n+(x.c[i]?1:0),0)});const pct=total?Math.round(done/total*100):0;const label=document.getElementById('progressLabel'),bar=document.getElementById('progressBar');if(label)label.textContent=pct+'%';if(bar)bar.style.width=pct+'%'}
function decorateFeatures(){[['today',teachingComplete()],['equipment',equipmentComplete()],['winddown',packComplete()]].forEach(([id,done])=>{const b=document.querySelector(`.feature-card[data-jump="${id}"]`);if(b){b.classList.toggle('phase-complete',done);const icon=b.querySelector('.icon');if(icon&&done)icon.textContent='➜'}})}
function addPaletteSettings(){const card=document.querySelector('#settings .card');if(!card||document.getElementById('paletteSetting'))return;const row=document.createElement('div');row.className='setting-row';row.id='paletteSetting';row.innerHTML='<div><strong>Colour palette</strong><small>Choose the look that suits you best. Saved on this device.</small></div><select class="select palette-choice" aria-label="Colour palette">'+Object.entries(palettes).map(([k,p])=>`<option value="${k}">${p.label}</option>`).join('')+'</select>';card.insertBefore(row,card.firstChild);row.querySelector('select').onchange=e=>applyPalette(e.target.value)}
function enhanceAll(){phaseDashboard();decorateChecklistRows();fixReorderClicks();decorateFeatures();addPaletteSettings();progress();applyPalette(localStorage.getItem(paletteKey)||'stjohn');const sel=document.getElementById('courseSelect');if(sel)sel.classList.add('course-selector-large')}
const originalUpdateAll=updateAll;updateAll=function(){originalUpdateAll();enhanceAll()};
const originalSave=save;save=function(){localStorage.setItem(stateKey,JSON.stringify(state));updateAll()};
document.getElementById('addTopic').onclick=()=>addNamed('teaching');document.getElementById('addPackDown').onclick=()=>addNamed('pack');document.getElementById('addEquipment').onclick=()=>addNamed('equipment');
setTimeout(enhanceAll,0);
})();