(()=>{
const css=document.createElement('style');css.textContent=`#teachViewCard{margin-top:0}.stage-list-row{display:flex;align-items:center;gap:12px;padding:14px 4px;border-top:1px solid #394650;min-height:66px}.stage-list-row input{width:32px;height:32px;min-width:32px;accent-color:#35c978;cursor:pointer}.stage-list-row.done .stage-list-text strong{text-decoration:line-through;color:#7f8993}.stage-list-text{flex:1;min-width:0}.stage-list-text strong{display:block;font-size:18px;line-height:1.3;font-weight:800}.stage-list-text small{display:block;margin-top:3px;color:#9eabb6;font-size:14px;line-height:1.35}.stage-list-controls{display:flex;gap:5px;flex-shrink:0}.stage-list-controls button{width:48px;height:48px;border:1px solid #43515d;background:#202a33;color:#d8e0e6;border-radius:10px;font-weight:900;font-size:18px;cursor:pointer}.stage-list-controls button:disabled{opacity:.35;cursor:not-allowed}.stage-list-controls .delete{color:#ff9a9f;border-color:#684047;background:#2b2529}.stage-list-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:16px;padding-top:16px;border-top:1px solid #394650}.stage-list-actions button{padding:10px 14px}.stage-complete-banner{margin-top:14px;padding:12px 14px;border-radius:10px;background:#173b2b;border:1px solid #2f8f60;color:#75e3aa;font-weight:800}.stage-view-head{display:flex;align-items:flex-start;justify-content:space-between;gap:15px}.stage-view-status{padding:9px 12px;border-radius:999px;background:#202f3b;color:#78baf0;font-size:13px;font-weight:800;white-space:nowrap}.stage-view-status.complete{background:#173b2b;color:#75e3aa}@media(max-width:650px){.stage-list-controls button{width:42px;height:42px}.stage-list-row{gap:9px}}`;document.head.appendChild(css);
function active(){return !!state.activeCourse&&state.activeCourse===state.course}
function items(){return editableTopics().map((x,i)=>({key:(i<course().topics.length?'b':'c')+(i<course().topics.length?i:i-course().topics.length),title:Array.isArray(x)?x[0]:x,detail:Array.isArray(x)?x[1]:''}))}
function checks(){state.checks=state.checks||{};state.checks[state.course]=state.checks[state.course]||{};return state.checks[state.course]}
function complete(){const a=items(),c=checks();return a.length>0&&a.every((_,i)=>!!c[i])}
function saveTeach(){localStorage.setItem(stateKey,JSON.stringify(state));window.updateAll?.();renderTeach()}
function move(i,d){const a=items(),j=i+d;if(j<0||j>=a.length)return;const base=course().topics,custom=state.customTopics[state.course]||[];const baseLen=base.length;if(i<baseLen&&j<baseLen){[base[i],base[j]]=[base[j],base[i]]}else if(i>=baseLen&&j>=baseLen){const x=i-baseLen,y=j-baseLen;[custom[x],custom[y]]=[custom[y],custom[x]]}else{return}const old=checks(),next={};a.forEach((_,k)=>{if(old[k]!==undefined)next[k===i?j:k===j?i:k]=old[k]});state.checks[state.course]=next;saveTeach()}
function renderTeach(){const host=document.getElementById('teach');if(!host||!active())return;let card=document.getElementById('teachViewCard');if(!card){card=document.createElement('div');card.id='teachViewCard';card.className='card';host.appendChild(card)}const a=items(),c=checks(),done=complete();card.innerHTML=`<div class="stage-view-head"><div><p class="eyebrow">TEACHING CHECKLIST</p><h3>${esc(course().name)} — Teaching checklist</h3><p class="muted">Work through each teaching topic and complete the required course activities.</p></div><span class="stage-view-status ${done?'complete':''}">${done?'COMPLETE':'IN PROGRESS'}</span></div><div class="today-phase-list">${a.map((x,i)=>`<div class="stage-list-row ${c[i]?'done':''}" data-index="${i}"><input type="checkbox" ${c[i]?'checked':''}><span class="stage-list-text"><strong>${esc(x.title)}</strong>${x.detail?`<small>${esc(x.detail)}</small>`:''}</span><span class="stage-list-controls"><button type="button" class="teach-up" ${i===0?'disabled':''}>▲</button><button type="button" class="teach-down" ${i===a.length-1?'disabled':''}>▼</button><button type="button" class="delete">✕</button></span></div>`).join('')}</div><div class="stage-list-actions"><button type="button" class="primary" id="teachSelectAll">✓ Select all</button><button type="button" class="primary" id="teachAdd">+ Add item</button><button type="button" class="ghost" onclick="printChecklist('teaching')">🖨 Print teaching checklist</button><button type="button" class="ghost" onclick="emailChecklist('teaching')">✉ Email a copy</button></div>${done?'<div class="stage-complete-banner">Teaching checklist complete — ready to move to Pack Down.</div>':''}`;
card.querySelectorAll('input[type=checkbox]').forEach(box=>box.onchange=()=>{const i=Number(box.closest('.stage-list-row').dataset.index);checks()[i]=box.checked;localStorage.setItem(stateKey,JSON.stringify(state));window.updateAll?.();renderTeach()});
card.querySelector('#teachSelectAll').onclick=()=>{a.forEach((_,i)=>checks()[i]=true);saveTeach()};
card.querySelector('#teachAdd').onclick=()=>{const n=prompt('Name the new teaching checklist item:');if(!n||!n.trim())return;state.customTopics[state.course]=state.customTopics[state.course]||[];state.customTopics[state.course].push([n.trim(),'']);saveTeach()};
card.querySelectorAll('.teach-up').forEach(b=>b.onclick=()=>move(Number(b.closest('.stage-list-row').dataset.index),-1));card.querySelectorAll('.teach-down').forEach(b=>b.onclick=()=>move(Number(b.closest('.stage-list-row').dataset.index),1));card.querySelectorAll('.delete').forEach(b=>b.onclick=()=>{const i=Number(b.closest('.stage-list-row').dataset.index),baseLen=course().topics.length;if(!confirm('Delete this teaching checklist item?'))return;if(i<baseLen){course().topics.splice(i,1)}else{state.customTopics[state.course].splice(i-baseLen,1)}state.checks[state.course]={};saveTeach()});}
function openTeach(e){if(!active())return;e?.preventDefault();e?.stopImmediatePropagation();if(typeof showView==='function')showView('teach');else{document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById('teach')?.classList.add('active')}setTimeout(renderTeach,40)}
window.renderTeachView=renderTeach;document.addEventListener('click',e=>{if(e.target.closest('#stageTeach'))openTeach(e)},true);document.addEventListener('DOMContentLoaded',()=>setTimeout(renderTeach,200));
})();
